# Generated by Django 5.0.3 on 2024-11-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='last_attempted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailbatch',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
