# Generated by Django 5.0.3 on 2024-11-10 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esender', '0002_scheduledemail_last_attempted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailbatch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailbatch',
            name='failed_emails',
        ),
        migrations.RemoveField(
            model_name='emailbatch',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='emailbatch',
            name='sent_emails',
        ),
        migrations.RemoveField(
            model_name='emailthrottle',
            name='emails_per_minute',
        ),
        migrations.RemoveField(
            model_name='scheduledemail',
            name='last_attempted',
        ),
        migrations.RemoveField(
            model_name='scheduledemail',
            name='retries',
        ),
        migrations.RemoveField(
            model_name='scheduledemail',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='emailthrottle',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailbatch',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailbatch',
            name='total_emails',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emailthrottle',
            name='emails_per_hour',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='email_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduledemail_set', to='esender.emailbatch'),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='EmailScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('default_schedule_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
