# Generated by Django 5.0.3 on 2024-11-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esender', '0003_remove_emailbatch_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemail',
            name='email_batch',
        ),
        migrations.RemoveField(
            model_name='emailscheduling',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailthrottle',
            name='user',
        ),
        migrations.RenameField(
            model_name='scheduledemail',
            old_name='scheduled_for',
            new_name='send_time',
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='EmailBatch',
        ),
        migrations.DeleteModel(
            name='EmailScheduling',
        ),
        migrations.DeleteModel(
            name='EmailThrottle',
        ),
    ]
