# Generated by Django 5.1.7 on 2025-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esender', '0005_emailstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledEmail',
        ),
        migrations.RemoveField(
            model_name='emailstatus',
            name='total_pending',
        ),
        migrations.AddField(
            model_name='emailstatus',
            name='user_email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
